pipeline:
  restore-cache:
    image: homerovalle/drone-gcs-cache
    pull: true
    restore: true
    bucket: rocket-cache
    secrets: [GCS_CACHE_JSON_KEY]
    mount:
      - /drone/.meteor/
      - ./node_modules
      - ./.meteor/local

  build:
    image: ubuntu:16.04
    environment:
      - METEOR_ALLOW_SUPERUSER=true
    commands:
      - apt update && apt install curl git python g++ build-essential bzip2 -y
      - export HOME=/drone
      - export PATH="/drone/.meteor:$PATH"
      - if [ ! -e "/drone/.meteor/meteor" ]; then export HOME=/drone; curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh; fi
      - which meteor
      - meteor npm install
      - set +e
      - meteor add rocketchat:lib
      - set -e
      - mkdir /drone/build
      - meteor build --allow-superuser --server-only --directory /drone/build
      - cp .docker/Dockerfile.local /drone/build/Dockerfile

  rebuild-cache:
    image: homerovalle/drone-gcs-cache
    pull: true
    rebuild: true
    bucket: rocket-cache
    secrets: [GCS_CACHE_JSON_KEY]
    mount:
      - /drone/.meteor/
      - ./node_modules
      - ./.meteor/local

  docker:
    image: plugins/gcr
    registry: us.gcr.io
    repo: aidbox2-205511/rocketchat
    dockerfile: /drone/build/Dockerfile
    storage_driver: overlay
    context: /drone/build
    tags: ${DRONE_COMMIT:0:8}
    secrets: [gcr_json_key]
    when:
      branch: develop

  flush_cache:
    image: homerovalle/drone-gcs-cache
    pull: true
    bucket: rocket-cache
    secrets: [GCS_CACHE_JSON_KEY]
    flush: true
    flush_age: 14
